company:
  name: "雁山老司机有限公司"
  address: "北京市海淀区科技园路88号"
  phone: "010-88889999"
  email: "yanshanlaosiji@gmail.com"
  
agreement:
  title: "自愿加班协议"
  terms:
    - "本人完全自愿参加公司安排的加班工作，不存在任何强制因素"
    - "本人已充分了解《中华人民共和国劳动法》关于工作时间和加班的相关规定"
    - "本人确认此次加班系出于个人意愿，非公司强制要求"
    - "本人同意按照公司规定获取相应的加班补偿"
    - "本协议自签署之日起生效"